# -*- coding: mbcs -*-
from part import *
from material import *
from section import *
from assembly import *
from step import *
from interaction import *
from load import *
from mesh import *
from optimization import *
from job import *
from sketch import *
from visualization import *
from connectorBehavior import *
mdb.models['Model-1'].ConstrainedSketch(name='__profile__', sheetSize=24.0)
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(-3.0, -2.0), point2=
    (-3.0, 2.0))
mdb.models['Model-1'].sketches['__profile__'].VerticalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['__profile__'].geometry[2])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(-3.0, 2.0), point2=(
    1.0, 2.0))
mdb.models['Model-1'].sketches['__profile__'].HorizontalConstraint(
    addUndoState=False, entity=
    mdb.models['Model-1'].sketches['__profile__'].geometry[3])
mdb.models['Model-1'].sketches['__profile__'].PerpendicularConstraint(
    addUndoState=False, entity1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[2], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[3])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(1.0, 2.0), point2=(
    1.0, 0.0))
mdb.models['Model-1'].sketches['__profile__'].VerticalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['__profile__'].geometry[4])
mdb.models['Model-1'].sketches['__profile__'].PerpendicularConstraint(
    addUndoState=False, entity1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[3], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[4])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(1.0, 0.0), point2=(
    3.0, 0.0))
mdb.models['Model-1'].sketches['__profile__'].HorizontalConstraint(
    addUndoState=False, entity=
    mdb.models['Model-1'].sketches['__profile__'].geometry[5])
mdb.models['Model-1'].sketches['__profile__'].PerpendicularConstraint(
    addUndoState=False, entity1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[4], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[5])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(3.0, 0.0), point2=(
    3.0, -2.0))
mdb.models['Model-1'].sketches['__profile__'].VerticalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['__profile__'].geometry[6])
mdb.models['Model-1'].sketches['__profile__'].PerpendicularConstraint(
    addUndoState=False, entity1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[5], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[6])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(3.0, -2.0), point2=(
    -3.0, -2.0))
mdb.models['Model-1'].sketches['__profile__'].HorizontalConstraint(
    addUndoState=False, entity=
    mdb.models['Model-1'].sketches['__profile__'].geometry[7])
mdb.models['Model-1'].sketches['__profile__'].PerpendicularConstraint(
    addUndoState=False, entity1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[6], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[7])
mdb.models['Model-1'].sketches['__profile__'].FilletByRadius(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[7], curve2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[2], nearPoint1=(
    -2.36577701568604, -2.04572534561157), nearPoint2=(-3.00110912322998, 
    -1.24413514137268), radius=0.25)
mdb.models['Model-1'].sketches['__profile__'].FilletByRadius(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[2], curve2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[3], nearPoint1=(
    -2.9843897819519, 1.61152982711792), nearPoint2=(-2.46609258651733, 
    2.02902507781982), radius=0.25)
mdb.models['Model-1'].sketches['__profile__'].FilletByRadius(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[3], curve2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[4], nearPoint1=(
    0.359464645385742, 1.9121265411377), nearPoint2=(0.994796752929688, 
    1.49463176727295), radius=0.25)
mdb.models['Model-1'].sketches['__profile__'].FilletByRadius(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[4], curve2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[5], nearPoint1=(
    1.04495429992676, 1.09383630752563), nearPoint2=(1.42949771881104, 
    0.0584487915039063), radius=0.25)
mdb.models['Model-1'].sketches['__profile__'].FilletByRadius(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[5], curve2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[6], nearPoint1=(
    1.56325244903564, 0.0417494773864746), nearPoint2=(2.98439025878906, 
    -0.509344100952148), radius=0.25)
mdb.models['Model-1'].sketches['__profile__'].FilletByRadius(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[6], curve2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[7], nearPoint1=(
    3.01782894134521, -1.47793221473694), nearPoint2=(1.84747982025146, 
    -1.94552683830261), radius=0.25)
mdb.models['Model-1'].sketches['__profile__'].DistanceDimension(entity1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[2], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[6], textPoint=(
    -0.225709915161133, -3.49860787391663), value=6.0)
mdb.models['Model-1'].sketches['__profile__'].DistanceDimension(entity1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[7], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[3], textPoint=(
    -5.50899982452393, 0.0584487915039063), value=4.0)
mdb.models['Model-1'].sketches['__profile__'].DistanceDimension(entity1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[3], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[5], textPoint=(
    4.68975639343262, 1.02703714370728), value=2.0)
mdb.models['Model-1'].sketches['__profile__'].DistanceDimension(entity1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[4], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[6], textPoint=(
    2.13170719146729, 3.06441259384155), value=2.0)
mdb.models['Model-1'].sketches['__profile__'].CircleByCenterPerimeter(center=(
    -2.75, -1.75), point1=(-2.625, -1.625))
mdb.models['Model-1'].sketches['__profile__'].CircleByCenterPerimeter(center=(
    -2.75, 0.0), point1=(-2.625, 0.125))
mdb.models['Model-1'].sketches['__profile__'].CircleByCenterPerimeter(center=(
    -2.75, 1.75), point1=(-2.625, 1.625))
mdb.models['Model-1'].sketches['__profile__'].CircleByCenterPerimeter(center=(
    0.75, 1.75), point1=(0.625, 1.625))
mdb.models['Model-1'].sketches['__profile__'].CircleByCenterPerimeter(center=(
    0.75, -0.25), point1=(0.625, -0.25))
mdb.models['Model-1'].sketches['__profile__'].CircleByCenterPerimeter(center=(
    2.75, -0.25), point1=(2.75, -0.375))
mdb.models['Model-1'].sketches['__profile__'].CircleByCenterPerimeter(center=(
    2.75, -1.75), point1=(2.625, -1.625))
mdb.models['Model-1'].sketches['__profile__'].HorizontalDimension(textPoint=(
    1.66624021530151, -0.923777103424072), value=2.0, vertex1=
    mdb.models['Model-1'].sketches['__profile__'].vertices[41], vertex2=
    mdb.models['Model-1'].sketches['__profile__'].vertices[28])
mdb.models['Model-1'].sketches['__profile__'].DistanceDimension(entity1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[5], entity2=
    mdb.models['Model-1'].sketches['__profile__'].vertices[41], textPoint=(
    -0.279041051864624, -0.16301965713501), value=0.25)
mdb.models['Model-1'].sketches['__profile__'].RadialDimension(curve=
    mdb.models['Model-1'].sketches['__profile__'].geometry[18], radius=0.1, 
    textPoint=(0.276753664016724, -0.913496494293213))
mdb.models['Model-1'].sketches['__profile__'].RadialDimension(curve=
    mdb.models['Model-1'].sketches['__profile__'].geometry[19], radius=0.1, 
    textPoint=(2.28378963470459, -0.59480094909668))
mdb.models['Model-1'].sketches['__profile__'].RadialDimension(curve=
    mdb.models['Model-1'].sketches['__profile__'].geometry[20], radius=0.1, 
    textPoint=(2.34554505348206, -1.4069607257843))
mdb.models['Model-1'].sketches['__profile__'].RadialDimension(curve=
    mdb.models['Model-1'].sketches['__profile__'].geometry[17], radius=0.1, 
    textPoint=(0.184121131896973, 1.14260506629944))
mdb.models['Model-1'].sketches['__profile__'].VerticalDimension(textPoint=(
    -1.9716055393219, 0.912257373332977), value=1.75, vertex1=
    mdb.models['Model-1'].sketches['__profile__'].vertices[13], vertex2=
    mdb.models['Model-1'].sketches['__profile__'].vertices[37])
mdb.models['Model-1'].sketches['__profile__'].DistanceDimension(entity1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[7], entity2=
    mdb.models['Model-1'].sketches['__profile__'].vertices[37], textPoint=(
    -3.58752799034119, -0.886832177639008), value=2.0)
mdb.models['Model-1'].sketches['__profile__'].undo()
mdb.models['Model-1'].sketches['__profile__'].RadialDimension(curve=
    mdb.models['Model-1'].sketches['__profile__'].geometry[16], radius=0.1, 
    textPoint=(-3.4125554561615, 0.881415784358978))
mdb.models['Model-1'].sketches['__profile__'].RadialDimension(curve=
    mdb.models['Model-1'].sketches['__profile__'].geometry[15], radius=0.1, 
    textPoint=(-3.43314051628113, -0.455050647258759))
mdb.models['Model-1'].sketches['__profile__'].RadialDimension(curve=
    mdb.models['Model-1'].sketches['__profile__'].geometry[14], radius=0.1, 
    textPoint=(-2.28161001205444, -1.04683327674866))
mdb.models['Model-1'].sketches['__profile__'].DistanceDimension(entity1=
    mdb.models['Model-1'].sketches['__profile__'].vertices[37], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[2], textPoint=(
    -2.72522735595703, -2.80900478363037), value=0.25)
mdb.models['Model-1'].sketches['__profile__'].CircleByCenterPerimeter(center=(
    0.0, -1.75), point1=(0.0, -1.625))
mdb.models['Model-1'].sketches['__profile__'].RadialDimension(curve=
    mdb.models['Model-1'].sketches['__profile__'].geometry[21], radius=0.1, 
    textPoint=(0.403198957443237, -2.28462076187134))
mdb.models['Model-1'].sketches['__profile__'].HorizontalDimension(textPoint=(
    1.43178939819336, -1.38565230369568), value=2.75, vertex1=
    mdb.models['Model-1'].sketches['__profile__'].vertices[45], vertex2=
    mdb.models['Model-1'].sketches['__profile__'].vertices[33])
mdb.models['Model-1'].sketches['__profile__'].VerticalDimension(textPoint=(
    -0.801676332950592, 0.755354404449463), value=2.0, vertex1=
    mdb.models['Model-1'].sketches['__profile__'].vertices[41], vertex2=
    mdb.models['Model-1'].sketches['__profile__'].vertices[18])
mdb.models['Model-1'].sketches['__profile__'].undo()
mdb.models['Model-1'].sketches.changeKey(fromName='__profile__', toName=
    'holePartSketch')
mdb.models['Model-1'].ConstrainedSketch(name='__profile__', sheetSize=200.0)
mdb.models['Model-1'].sketches['__profile__'].sketchOptions.setValues(
    gridOrigin=(-0.409621715545655, -0.217097640037539))
mdb.models['Model-1'].sketches['__profile__'].retrieveSketch(sketch=
    mdb.models['Model-1'].sketches['holePartSketch'])
mdb.models['Model-1'].Part(dimensionality=THREE_D, name='stuff', type=
    DEFORMABLE_BODY)
mdb.models['Model-1'].parts['stuff'].BaseShell(sketch=
    mdb.models['Model-1'].sketches['__profile__'])
del mdb.models['Model-1'].sketches['__profile__']
mdb.models['Model-1'].Material(name='Glass')
mdb.models['Model-1'].materials['Glass'].Density(table=((0.000149528410397976, 
    ), ))
# Save by ctf365 on 2018_10_29-15.56.33; build 2018 2017_11_07-11.21.41 127140
